### PR TITLE
Revert "storage: retry calls"

### PR DESCRIPTION
**Pull request by joshk0**
This reverts commit 61a09b43cee7329f083691f0b048d7707f538191.

This will probably help with the Gazette storage issue.

/cc @mharris717

---
This change is [Reviewable](https://reviewable.io/reviews/arbortech/google-cloud-go/1)

### CODE REVIEW

**Comment by jgraettinger** [comment]
I agree this is probably it. I'd like to catch it in the act using tracing, if I can, and then apply this patch to resolve until fixed in the upstream.

My current guess: it's retrying a portion of a multi-part upload which overall has failed and can't be retried.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/arbortech/google-cloud-go/1#-:-KaEchtja9FaWFP0meQA:bdmtozq)*

**Comment by jgraettinger** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/writer.go, line 96 at r1](https://reviewable.io:443/reviews/arbortech/google-cloud-go/1#-KaKMxYVhSSoLpem9bow:-KaKMxYVhSSoLpem9box:bvb0bcv) ([raw file](https://github.com/arbortech/google-cloud-go/blob/b7d017c18a47bfd8b8c528ac26002fe988c97e68/storage/writer.go#L96)):*
> ```Go
> 		err := applyConds("NewWriter", w.o.gen, w.o.conds, call)
> 		if err == nil {
> 			err = runWithRetry(w.ctx, func() error { resp, err = call.Do(); return err })
> ```

this one is the major no-no. `pr`, above, gets wrapped in a chunking reader, and once a single chunk upload has completed it's not possible to retry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/arbortech/google-cloud-go/1)*

**Comment by jgraettinger** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/arbortech/google-cloud-go/1#-:-KaKNMSZeP1Glv8UmZYm:bnfp4nl)*

**Comment by joshk0** [comment]
Can you find some way to upstream this? No need to write code, but maybe
chime in on the ticket I linked earlier.

**Comment by joshk0** [comment]
Never mind! Saw you took care of this already.

**Pull request merged**
